export const ALL_CHATROOMS_REQUEST = "ALL_CHATROOMS_REQUEST";
export const ALL_CHATROOMS_SUCCESS = "ALL_CHATROOMS_SUCCESS";
export const ALL_CHATROOMS_FAIL = "ALL_CHATROOMS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
